defaults:
  - _self_
  - task: one_theorem
  - device: gpu
  - hydra: default
  - paths: eddie

seed: 27
save_dir: "runs/"

logger:
  _target_: pytorch_lightning.loggers.WandbLogger
  name: ${now:%Y-%m-%d}_${now:%H-%M-%S}
  project: "gfn4ntp"
  save_dir: ${save_dir}
  offline: False
